In [1]:
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
def clean_text(text):

    # 1. Convert to lowercase
    text = text.lower()

    # 2. Remove numbers
    text = re.sub(r'\d+', '', text)

    # 3. Remove punctuation & special characters
    text = re.sub(r'[^\w\s]', '', text)

    # 4. Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # 5. Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = text.split()
    words = [word for word in words if word not in stop_words]

    # 6. Lemmatization
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [4]:
resume_df = pd.read_csv("dataset/Resume.csv")
print(resume_df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [5]:
resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [7]:
print(resume_df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [8]:
resume_df['cleaned_resume'] = resume_df['Resume_str'].apply(clean_text)

In [9]:
resume_df['Resume_str']

0                HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1                HR SPECIALIST, US HR OPERATIONS      ...
2                HR DIRECTOR       Summary      Over 2...
3                HR SPECIALIST       Summary    Dedica...
4                HR MANAGER         Skill Highlights  ...
                              ...
2479             RANK: SGT/E-5 NON- COMMISSIONED OFFIC...
2480             GOVERNMENT RELATIONS, COMMUNICATIONS ...
2481             GEEK SQUAD AGENT         Professional...
2482             PROGRAM DIRECTOR / OFFICE MANAGER    ...
2483             STOREKEEPER II       Professional Sum...
Name: Resume_str, Length: 2484, dtype: object

In [10]:
resume_df.to_csv("cleaned_resume.csv", index=False)

In [11]:
job_df = pd.read_csv("dataset/job_title_des.csv")
print(job_df.columns)

Index(['Unnamed: 0', 'Job Title', 'Job Description'], dtype='object')

In [13]:
job_df.columns = job_df.columns.str.strip()   # remove extra spaces (safe step)

job_df['cleaned_job'] = job_df['Job Description'].apply(clean_text)

In [14]:
job_df.to_csv("cleaned_jobs.csv", index=False)

In [16]:
job_df.head(1)

,Unnamed: 0,Job Title,Job Description,cleaned_job
0,0,Flutter Developer,We are looking for hire experts flutter develo...,looking hire expert flutter developer eligible...

In [19]:
print(resume_df['Resume_str'].iloc[0])
print(clean_text(resume_df['Resume_str'].iloc[0]))

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.
hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certified ihg customer loyalty marketing segment hilton worldwide general manager training certification accomplished trainer cross server hospitality system hilton onq micros opera pm fidelio opera reservation system or holidex completed course seminar customer service sale strategy inventory control loss prevention safety time management leadership performance assessment experience hr administratormarketing associate hr administrator dec current company name city state help develop policy directs coordinate activity employment compensation labor relation benefit training employee service prepares employee separation notice related documentation keep record benefit plan participation insurance pension plan personnel transaction hire promotion transfer performance review termination employee statistic government reporting advises management appropriate resolution employee relation issue administers benefit program life health dental insurance pension plan vacation sick leave leave absence employee assistance marketing associate designed created marketing collateral sale meeting trade show company executive managed inhouse advertising program consisting print medium collateral piece assisted complete design launch company website month created official company page facebook facilitate interaction customer analyzed rating programming feature competitor evaluate effectiveness marketing strategy advanced medical claim analyst mar dec company name city state reviewed medical bill accuracy treatment test hospital stay prior sanctioning claim trained interpret code icd cpt terminology commonly used medical billing fully understand paperwork submitted healthcare provider required organizational analytical skill well computer skill knowledge medical terminology procedure statistic billing standard data analysis law regarding medical billing assistant general manager jun dec company name city state performed duty including limited budgeting financial management accounting human resource payroll purchasing established maintained close working relationship department hotel ensure maximum operation productivity morale guest service handled daily operation reported directly corporate office hired trained staff overall objective goal emphasis high customer service marketing advertising working public relation medium government local business chamber commerce executive support marketing assistant jul jun company name city state provided assistance various department head executive marketing customer service human resource managed frontend operation ensure friendly efficient transaction ensured swift resolution customer issue preserve customer loyalty complying company policy exemplified secondtonone customer service delivery interaction customer potential client reservation front office manager jun jul company name city state owner partner dec may company name city state price integrity coordinator aug dec company name city state education na business administration jefferson college city state business administration marketing advertising high school diploma college prep study sainte genevieve senior high city state awarded american shrubel leadership scholarship jefferson college skill accounting ad advertising analytical skill benefit billing budgeting client customer service data analysis delivery documentation employee relation financial management government relation human resource insurance labor relation layout marketing marketing collateral medical billing medical terminology office organizational payroll performance review personnel policy poster presentation public relation purchasing reporting statistic website

In [20]:
print(resume_df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category', 'cleaned_resume'], dtype='object')